/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_2;

import java.util.Scanner;

public class App {
    public static final double convK = 273.15;
    public static final double convF1 = 1.8;
    public static final double convF2 = 32.0;    

    public static void main(String[] args) {
        Scanner consola = new Scanner (System.in);
        System.out.println("Introducir grados centígrados");
        double gradosC = consola.nextDouble();
        double gradosF = (gradosC * convF1) + convF2;
        double gradosK = (gradosC + convK);
        System.out.println("grados Fahrenheit = " + gradosF + " F");
        System.out.println("grados Kelvin = " + gradosK + " K");
        
        
    }

    
}
