/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_5;

import java.util.Scanner;

public class App {
 
    public static void main(String[] args) {
        Scanner consola = new Scanner (System.in);
        System.out.println("Introducir sueldo fijo");
        double dineroFijo = consola.nextDouble();
        System.out.println("Introducir importe de ventas");
        int importeVentas = consola.nextInt();
        System.out.println("Introducir numero de kilometros");
        int numeroKilometros = consola.nextInt();
        System.out.println("Introducir dias desplazados");
        int numeroDias = consola.nextInt();
        //dinero adicional sueldo bruto
        double dineroVentas = importeVentas * 0.05;
        double dineroKilometros = numeroKilometros * 2;
        double dineroDias = numeroDias * 30;
        //total dinero bruto
        double dineroBruto = dineroFijo + dineroDias + dineroKilometros + dineroVentas;
        System.out.println("Sueldo bruto a percibir = " + dineroBruto);
        //dinero liquido aplicado con los impuestos
        double liquidoImpu1 = dineroBruto * 0.82;
        double liquidoImpu2 = (liquidoImpu1 - 36);
        System.out.println("Liquido a percibir = " + liquidoImpu2);
        
        
        
        
        
        
               

    }
}
